export * from './pages/MarvelPage'
export * from './pages/DcPage'
export * from './pages/SearchPage'
export * from './pages/HeroPage'
// export * from './components/Navbar'
export * from './components'
export*from './routes/HeroesRoutes'